#include QMK_KEYBOARD_H
#if __has_include("keymap.h")
#    include "keymap.h"
#endif


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT(KC_ESC, KC_F11, KC_NO, KC_MSTP, KC_NO, KC_NO, KC_MRWD, KC_MFFD, KC_NO, KC_MPLY, KC_MPLY, KC_MNXT, KC_MUTE, KC_NO, KC_NO, RM_TOGG)
};

bool process_record_user(uint16_t keycode, keyrecord_t *record) {
    if (record->event.pressed) {
        switch (keycode) {
            case QK_MACRO_0:
                SEND_STRING(SS_DOWN(X_MS_BTN3)SS_TAP(X_MS_LEFT)SS_UP(X_MS_BTN3));
                return false;
            case QK_MACRO_1:
                SEND_STRING(SS_DOWN(X_MS_BTN3)SS_TAP(X_MS_RGHT)SS_UP(X_MS_BTN3));
                return false;
            case QK_MACRO_2:
                SEND_STRING(SS_DOWN(X_MS_BTN3)SS_TAP(X_MS_UP)SS_UP(X_MS_BTN3));
                return false;
            case QK_MACRO_3:
                SEND_STRING(SS_DOWN(X_MS_BTN3)SS_TAP(X_MS_DOWN)SS_UP(X_MS_BTN3));
                return false;
            case QK_MACRO_4:
                SEND_STRING(SS_DOWN(X_MS_BTN2)SS_TAP(X_MS_LEFT)SS_UP(X_MS_BTN2));
                return false;
            case QK_MACRO_5:
                SEND_STRING(SS_DOWN(X_MS_BTN2)SS_TAP(X_MS_RGHT)SS_UP(X_MS_BTN2));
                return false;
            case QK_MACRO_6:
                SEND_STRING(SS_DOWN(X_MS_BTN2)SS_TAP(X_MS_UP)SS_UP(X_MS_BTN2));
                return false;
            case QK_MACRO_7:
                SEND_STRING(SS_DOWN(X_MS_BTN2)SS_TAP(X_MS_DOWN)SS_UP(X_MS_BTN2));
                return false;
        }
    }

    return true;
};


#ifdef OTHER_KEYMAP_C
#    include OTHER_KEYMAP_C
#endif // OTHER_KEYMAP_C

